# check_wav.py - 读取 WAV 文件头信息
with open("start.wav", "rb") as f:
     header = f.read(44)
     print("=== WAV Header ===")
     riff = header[0:4].decode('ascii', errors='replace')
     wave = header[8:12].decode('ascii', errors='replace')
     fmt_tag = header[20] | (header[21] << 8)
     channels = header[22] | (header[23] << 8)
     sample_rate = header[24] | (header[25]<<8) | (header[26]<<16) | (header[27]<<24)
     bits_per_sample = header[34] | (header[35] << 8)
     data_size = header[40] | (header[41]<<8) | (header[42]<<16) | (header[43]<<24)
     print("RIFF:", riff)
     print("WAVE:", wave)
     print("Format:", fmt_tag, "(1=PCM)")
     print("Channels:", channels)
     print("Sample Rate:", sample_rate, "Hz")
     print("Bits/Sample:", bits_per_sample)
     print("Data Size:", data_size, "bytes")
     print("Duration: ~", data_size / channels / (bits_per_sample//8) / sample_rate, "s")
